included:
    - Sources
    - Tests
    - OverlayAppUITests

excluded:
    - output

opt_in_rules:
    - array_init
    - attributes
    - closure_end_indentation
    - closure_spacing
    - colon
    - contains_over_first_not_nil
    - discouraged_optional_collection
    - empty_count
    - explicit_init
    - explicit_type_interface
    - fallthrough
    - file_header
    - first_where
    - lower_acl_than_parent
    - nimble_operator
    - number_separator
    - object_literal
    - operator_usage_whitespace
    - overridden_super_call
    - override_in_extension
    - private_action
    - private_outlet
    - prohibited_super_call
    - redundant_nil_coalescing
    - required_enum_case
    - sorted_first_last
    - sorted_imports
    - untyped_error_in_catch

attributes:
    always_on_same_line:
        - "@IBDesignable"
        - "@nonobjc"
        - "@objc"
        - "@IBAction"
        - "@IBInspectable"
        - "@IBOutlet"

disabled_rules:
    - weak_delegate
    - opening_brace
    - closure_end_indentation
    - statement_position

explicit_type_interface:
    excluded:
        - local

line_length:
    ignores_function_declarations: true
    ignores_comments: true

number_separator:
    minimum_length: 5

identifier_name:
    min_length: 1

file_header:
    required_pattern: \/\/ Copyright \(c\) \d{4} Manabu Nakazawa. Licensed under the MIT license. See LICENSE in the project root for license information.
