name: Daily GitHub Trending Update

on:
  schedule:
    # Esegui ogni giorno alle 02:00 UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Permette anche l'esecuzione manuale
  push: # Aggiungi questo trigger
    branches:
      - main # Esegui solo su push al branch 'main' (modifica se il tuo branch principale ha un altro nome)


jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Generate RSS feeds and website
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python src/main.py
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add feeds/ data/ index.html
          git diff --quiet && git diff --staged --quiet || git commit -m "Daily update: $(date +%Y-%m-%d)"
          git push
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          keep_files: true