name: Fetch and Generate RSS Feeds

on:
  schedule:
    - cron:  '0 1 * * *'
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      env:
        USER_GITHUB_CLIENT_ID: ${{ secrets.USER_GITHUB_CLIENT_ID }}
        USER_GITHUB_CLIENT_SECRET: ${{ secrets.USER_GITHUB_CLIENT_SECRET }}
      run: ./build.sh
    - name: Deploy
      env:
        USER_GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}
      run: ./deploy.sh
